backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "src/assets" # Media files will be stored in the repo under /src/assets/
public_folder: "/src/assets/" # The src attribute for uploaded media will begin with /src/assets/


collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored 
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string"}
      - { label: 'Description', name: 'excerpt', hint: 'Description', widget: 'string' }
      - { label: "Publish Date", name: "publishDate", widget: "datetime"}
      - { label: "Featured Image", name: "image", widget: "image"}
      - { label: "Source", name: "source", widget: "string", required: false}
      - { label: 'Category', name: 'category', widget: 'select', multiple: true, options: ["gaming", "streaming", "wfh", "couples"], hint: 'Category' }
      - { label: "Author", name: "author", widget: 'select', options: ["daniel"], hint: 'Author', default: "daniel" }
      - { label: "Tags", name: "tags", widget: "list", field: { name: "tag", widget: "string" } }
      - label: "Images with Dots"
        name: "imagesWithDots"
        widget: "list"
        fields:
          - { label: "Image Source", name: "src", widget: "image" }
          - label: "Dots"
            name: "dots"
            widget: "list"
            fields:
              - { label: "Top Position", name: "top", widget: "number", min: 1, max: 100, step: 5, value_type: "int", hint: "e.g. 50%" }
              - { label: "Left Position", name: "left", widget: "number", min: 1, max: 100, step: 5, value_type: "int", hint: "e.g. 25%" }
              - { label: "Link", name: "link", widget: "string", required: false }
              - { label: "Tooltip Text", name: "text", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "topnav"
    label: "Top Navigation"
    files:
      - file: "src/data/menu.yml"
        label: "Menu"
        name: "menu"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Href", name: "href", widget: "string" }
          - { label: "External", name: "external", widget: "boolean", default: false }
          - { label: "Badge", name: "badge", widget: "string", required: false }